/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fundamentos.tallerbasededatos;

/**
 *
 * @author Juan Pablo
 */
public class Procedure extends javax.swing.JFrame {

    /**
     * Creates new form Procedure
     */
    String user;
    String password;

    public Procedure(String user, String password) {
        initComponents();
        this.user = user;
        this.password = password;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelMuestra = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Mmodificar = new javax.swing.JMenu();
        Meliminar = new javax.swing.JMenu();
        Mconsultar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout PanelMuestraLayout = new javax.swing.GroupLayout(PanelMuestra);
        PanelMuestra.setLayout(PanelMuestraLayout);
        PanelMuestraLayout.setHorizontalGroup(
            PanelMuestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );
        PanelMuestraLayout.setVerticalGroup(
            PanelMuestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelMuestra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelMuestra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Ingresar datos");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        Mmodificar.setText("Actualizar");
        Mmodificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MmodificarMouseClicked(evt);
            }
        });
        jMenuBar1.add(Mmodificar);

        Meliminar.setText("Eliminar");
        Meliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MeliminarMouseClicked(evt);
            }
        });
        jMenuBar1.add(Meliminar);

        Mconsultar.setText("Consultar");
        Mconsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MconsultarMouseClicked(evt);
            }
        });
        jMenuBar1.add(Mconsultar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MconsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MconsultarMouseClicked
        FormularioConsulta fc = new FormularioConsulta(user, password);
        fc.setSize(536, 384);
        PanelMuestra.removeAll();
        PanelMuestra.add(fc);
        PanelMuestra.revalidate();
        PanelMuestra.repaint();
    }//GEN-LAST:event_MconsultarMouseClicked

    private void MeliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MeliminarMouseClicked
        formularioEliminar fe = new formularioEliminar(user, password);
        fe.setSize(536, 384);
        PanelMuestra.removeAll();
        PanelMuestra.add(fe);
        PanelMuestra.revalidate();
        PanelMuestra.repaint();
    }//GEN-LAST:event_MeliminarMouseClicked

    private void MmodificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MmodificarMouseClicked
        FormularioModificar fm = new FormularioModificar(user, password);
        fm.setSize(536, 384);
        PanelMuestra.removeAll();
        PanelMuestra.add(fm);
        PanelMuestra.revalidate();
        PanelMuestra.repaint();
    }//GEN-LAST:event_MmodificarMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        FormularioInsertar fi = new FormularioInsertar(user, password);
        fi.setSize(536, 384);
        PanelMuestra.removeAll();
        PanelMuestra.add(fi);
        PanelMuestra.revalidate();
        PanelMuestra.repaint();
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Mconsultar;
    private javax.swing.JMenu Meliminar;
    private javax.swing.JMenu Mmodificar;
    private javax.swing.JPanel PanelMuestra;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
